name: Build Linux Binaries

on:
  push:
  workflow_dispatch:

jobs:
  Blint-Build:
    runs-on: ubuntu-latest
    steps:
    - name: Install poetry
      run: |
        git config --global init.defaultBranch main
        git init .
        git remote add origin https://git.sr.ht/~prabhu/blint
        git config gc.auto 0
        git config --get-all http.https://git.sr.ht/~prabhu/blint.extraheader
        git fetch --force --tags --prune --prune-tags --progress --no-recurse-submodules origin
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install rust minimal nightly
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
    - name: Install poetry
      run: |
        python3 -m pip install twine setuptools wheel pyoxidizer
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python3 -
        poetry export -f requirements.txt > requirements-dist.txt
    - name: Binary build
      run: |
        rustup target add x86_64-unknown-linux-gnu
        pyoxidizer build --release --target-triple x86_64-unknown-linux-gnu
        ./build/x86_64-unknown-linux-gnu/release/install/blint -i ./build/x86_64-unknown-linux-gnu/release/install/blint -o reports        
