name: Build Mac Binaries

on:
  push:
  workflow_dispatch:

jobs:
  Blint-Build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      run: |
        git clone https://git.sr.ht/~prabhu/blint --depth=1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install rust minimal nightly
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
    - name: Install poetry
      run: |
        python3 -m pip install twine setuptools wheel pyoxidizer
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python3 -
        cd blint
        ~/.local/bin/poetry export -f requirements.txt > requirements-dist.txt
    - name: Binary darwin build
      run: |
        rustup target add x86_64-apple-darwin
        cd blint
        pyoxidizer build --release --target-triple x86_64-apple-darwin
        ./build/x86_64-apple-darwin/release/install/blint -i ./build/x86_64-apple-darwin/release/install/blint -o reports
    - name: Binary arm64 darwin build
      run: |
        rustup target add aarch64-apple-darwin
        cd blint
        pyoxidizer build --release --target-triple aarch64-apple-darwin
        ./build/aarch64-apple-darwin/release/install/blint -i ./build/aarch64-apple-darwin/release/install/blint -o reports        
    - uses: actions/upload-artifact@v1
      with:
        path: |
          ./blint/build/x86_64-apple-darwin/release/install
          ./blint/build/aarch64-apple-darwin/release/install
        name: blint-bin-darwin
