name: Python matrix CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        python-version: ['3.6', '3.8', '3.9']
    steps:
    - name: Checkout
      run: |
        git clone https://git.sr.ht/~prabhu/blint
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install poetry
      run: |
        python3 -m pip install twine setuptools wheel
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python3 -
        cd blint
        ~/.local/bin/poetry install
    - name: Test with pytest
      run: |
        cd blint
        ~/.local/bin/poetry run pytest --cov=blint tests
    - name: Lint with flake8
      run: |
        cd blint
        # stop the build if there are Python syntax errors or undefined names
        ~/.local/bin/poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        ~/.local/bin/poetry run flake8 . --count --exit-zero --statistics

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]
    steps:
      - name: Checkout
        run: |
          git clone https://git.sr.ht/~prabhu/blint
      - name: Install poetry
        run: |
          python3 -m pip install twine setuptools wheel
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python3 -
          cd blint
          ~/.local/bin/poetry install
          ~/.local/bin/poetry export -f requirements.txt -o requirements.txt
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.2.2
        with:
          package-dir: blint
      - uses: actions/upload-artifact@v2
        with:
          path: ./blint/wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone https://git.sr.ht/~prabhu/blint
      - name: Install poetry
        run: |
          python3 -m pip install twine setuptools wheel
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python3 -
          cd blint
          ~/.local/bin/poetry install
          ~/.local/bin/poetry export -f requirements.txt -o requirements.txt
      - name: Build sdist
        run: |
          cd blint
          pipx run build --sdist
      - uses: actions/upload-artifact@v2
        with:
          path: ./blint/dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
