name: Scan Potential Malware

on:
  schedule:
    - cron: 0 */6 * * *
  workflow_dispatch:

jobs:
  Blint-Scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install blint
      run: |
        pip install blint
    - name: Download binaries
      run: |
        mkdir malware
        cd malware
        curl -L "https://urlhaus.abuse.ch/downloads/text_online/" -o links.txt
        grep "\.(exe\|dll\)" links.txt | head -20 > exe-links.txt
        wget -i exe-links.txt
        for i in `ls "*.zip"`; do
          unzip $i
        done
    - name: Perform scan
      run: |
        blint -i malware -o reports
    - uses: actions/upload-artifact@v1
      with:
        path: ./reports
        name: blint-reports
