name: Build Windows Binaries

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * *"

jobs:
  Blint-Build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      run: |
        git clone https://git.sr.ht/~prabhu/blint --depth=1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install rust minimal nightly
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly    
    - name: Install poetry
      run: |
        python -m pip install twine setuptools wheel pyoxidizer
        (Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py -UseBasicParsing).Content | python -
        cd blint
        C:\Users\runneradmin\AppData\Roaming\Python\Scripts\poetry export -f requirements.txt > requirements-dist.txt
    - name: Binary windows build
      run: |
        rustup target add x86_64-pc-windows-msvc
        cd blint
        pyoxidizer build --release --target-triple x86_64-pc-windows-msvc
    - uses: actions/upload-artifact@v1
      with:
        path: blint/build/x86_64-pc-windows-msvc/release/install
        name: blint-bin-windows
